//------------------------------------------------------------------------------
// <auto-generated>
//     Esse código foi gerado por uma ferramenta.
//
//     As alterações no arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CFM
{
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servico.cfm.org.br/")]
    public partial class Exception
    {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servico.cfm.org.br/")]
    public partial class medicoVO
    {
        
        private string codigoErroField;
        
        private string crmField;
        
        private string dataAtualizacaoField;
        
        private string dataNascimentoField;
        
        private string[] especialidadeField;
        
        private byte[] imagemField;
        
        private string nomeField;
        
        private string numeroCPFField;
        
        private string situacaoField;
        
        private string tipoInscricaoField;
        
        private string ufField;
        
        private string verificarAutoriazacaoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string codigoErro
        {
            get
            {
                return this.codigoErroField;
            }
            set
            {
                this.codigoErroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string crm
        {
            get
            {
                return this.crmField;
            }
            set
            {
                this.crmField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string dataAtualizacao
        {
            get
            {
                return this.dataAtualizacaoField;
            }
            set
            {
                this.dataAtualizacaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string dataNascimento
        {
            get
            {
                return this.dataNascimentoField;
            }
            set
            {
                this.dataNascimentoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("especialidade", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public string[] especialidade
        {
            get
            {
                return this.especialidadeField;
            }
            set
            {
                this.especialidadeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=5)]
        public byte[] imagem
        {
            get
            {
                return this.imagemField;
            }
            set
            {
                this.imagemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string nome
        {
            get
            {
                return this.nomeField;
            }
            set
            {
                this.nomeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string numeroCPF
        {
            get
            {
                return this.numeroCPFField;
            }
            set
            {
                this.numeroCPFField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string situacao
        {
            get
            {
                return this.situacaoField;
            }
            set
            {
                this.situacaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string tipoInscricao
        {
            get
            {
                return this.tipoInscricaoField;
            }
            set
            {
                this.tipoInscricaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string uf
        {
            get
            {
                return this.ufField;
            }
            set
            {
                this.ufField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string verificarAutoriazacao
        {
            get
            {
                return this.verificarAutoriazacaoField;
            }
            set
            {
                this.verificarAutoriazacaoField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://servico.cfm.org.br/", ConfigurationName="CFM.ServicoConsultaMedicos")]
    public interface ServicoConsultaMedicos
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(CFM.Exception), Action="", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CFM.ConsultarResponse> ConsultarAsync(CFM.Consultar request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(CFM.Exception), Action="", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CFM.ValidarResponse> ValidarAsync(CFM.Validar request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(CFM.Exception), Action="", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CFM.ConsultaCompletaResponse> ConsultaCompletaAsync(CFM.ConsultaCompleta request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(CFM.Exception), Action="", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CFM.buscarImagemResponse> buscarImagemAsync(CFM.buscarImagem request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Consultar", WrapperNamespace="http://servico.cfm.org.br/", IsWrapped=true)]
    public partial class Consultar
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servico.cfm.org.br/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int crm;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servico.cfm.org.br/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string uf;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servico.cfm.org.br/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string chave;
        
        public Consultar()
        {
        }
        
        public Consultar(int crm, string uf, string chave)
        {
            this.crm = crm;
            this.uf = uf;
            this.chave = chave;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarResponse", WrapperNamespace="http://servico.cfm.org.br/", IsWrapped=true)]
    public partial class ConsultarResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servico.cfm.org.br/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CFM.medicoVO dadosMedico;
        
        public ConsultarResponse()
        {
        }
        
        public ConsultarResponse(CFM.medicoVO dadosMedico)
        {
            this.dadosMedico = dadosMedico;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Validar", WrapperNamespace="http://servico.cfm.org.br/", IsWrapped=true)]
    public partial class Validar
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servico.cfm.org.br/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int crm;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servico.cfm.org.br/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string uf;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servico.cfm.org.br/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cpf;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servico.cfm.org.br/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string dataNascimento;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servico.cfm.org.br/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string chave;
        
        public Validar()
        {
        }
        
        public Validar(int crm, string uf, string cpf, string dataNascimento, string chave)
        {
            this.crm = crm;
            this.uf = uf;
            this.cpf = cpf;
            this.dataNascimento = dataNascimento;
            this.chave = chave;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ValidarResponse", WrapperNamespace="http://servico.cfm.org.br/", IsWrapped=true)]
    public partial class ValidarResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servico.cfm.org.br/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool resultadoConsulta;
        
        public ValidarResponse()
        {
        }
        
        public ValidarResponse(bool resultadoConsulta)
        {
            this.resultadoConsulta = resultadoConsulta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultaCompleta", WrapperNamespace="http://servico.cfm.org.br/", IsWrapped=true)]
    public partial class ConsultaCompleta
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servico.cfm.org.br/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int crm;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servico.cfm.org.br/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string uf;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servico.cfm.org.br/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cpf;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servico.cfm.org.br/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string dataNascimento;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servico.cfm.org.br/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string chave;
        
        public ConsultaCompleta()
        {
        }
        
        public ConsultaCompleta(int crm, string uf, string cpf, string dataNascimento, string chave)
        {
            this.crm = crm;
            this.uf = uf;
            this.cpf = cpf;
            this.dataNascimento = dataNascimento;
            this.chave = chave;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultaCompletaResponse", WrapperNamespace="http://servico.cfm.org.br/", IsWrapped=true)]
    public partial class ConsultaCompletaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servico.cfm.org.br/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CFM.medicoVO dadosMedico;
        
        public ConsultaCompletaResponse()
        {
        }
        
        public ConsultaCompletaResponse(CFM.medicoVO dadosMedico)
        {
            this.dadosMedico = dadosMedico;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="buscarImagem", WrapperNamespace="http://servico.cfm.org.br/", IsWrapped=true)]
    public partial class buscarImagem
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servico.cfm.org.br/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cpf;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servico.cfm.org.br/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string chave;
        
        public buscarImagem()
        {
        }
        
        public buscarImagem(string cpf, string chave)
        {
            this.cpf = cpf;
            this.chave = chave;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="buscarImagemResponse", WrapperNamespace="http://servico.cfm.org.br/", IsWrapped=true)]
    public partial class buscarImagemResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servico.cfm.org.br/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CFM.medicoVO resultadoImagem;
        
        public buscarImagemResponse()
        {
        }
        
        public buscarImagemResponse(CFM.medicoVO resultadoImagem)
        {
            this.resultadoImagem = resultadoImagem;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface ServicoConsultaMedicosChannel : CFM.ServicoConsultaMedicos, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class ServicoConsultaMedicosClient : System.ServiceModel.ClientBase<CFM.ServicoConsultaMedicos>, CFM.ServicoConsultaMedicos
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar o ponto de extremidade de serviço.
        /// </summary>
        /// <param name="serviceEndpoint">O ponto de extremidade a ser configurado</param>
        /// <param name="clientCredentials">As credenciais do cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServicoConsultaMedicosClient() : 
                base(ServicoConsultaMedicosClient.GetDefaultBinding(), ServicoConsultaMedicosClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.ServicoConsultaMedicosPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicoConsultaMedicosClient(EndpointConfiguration endpointConfiguration) : 
                base(ServicoConsultaMedicosClient.GetBindingForEndpoint(endpointConfiguration), ServicoConsultaMedicosClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicoConsultaMedicosClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServicoConsultaMedicosClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicoConsultaMedicosClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServicoConsultaMedicosClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicoConsultaMedicosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CFM.ConsultarResponse> CFM.ServicoConsultaMedicos.ConsultarAsync(CFM.Consultar request)
        {
            return base.Channel.ConsultarAsync(request);
        }
        
        public System.Threading.Tasks.Task<CFM.ConsultarResponse> ConsultarAsync(int crm, string uf, string chave)
        {
            CFM.Consultar inValue = new CFM.Consultar();
            inValue.crm = crm;
            inValue.uf = uf;
            inValue.chave = chave;
            return ((CFM.ServicoConsultaMedicos)(this)).ConsultarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CFM.ValidarResponse> CFM.ServicoConsultaMedicos.ValidarAsync(CFM.Validar request)
        {
            return base.Channel.ValidarAsync(request);
        }
        
        public System.Threading.Tasks.Task<CFM.ValidarResponse> ValidarAsync(int crm, string uf, string cpf, string dataNascimento, string chave)
        {
            CFM.Validar inValue = new CFM.Validar();
            inValue.crm = crm;
            inValue.uf = uf;
            inValue.cpf = cpf;
            inValue.dataNascimento = dataNascimento;
            inValue.chave = chave;
            return ((CFM.ServicoConsultaMedicos)(this)).ValidarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CFM.ConsultaCompletaResponse> CFM.ServicoConsultaMedicos.ConsultaCompletaAsync(CFM.ConsultaCompleta request)
        {
            return base.Channel.ConsultaCompletaAsync(request);
        }
        
        public System.Threading.Tasks.Task<CFM.ConsultaCompletaResponse> ConsultaCompletaAsync(int crm, string uf, string cpf, string dataNascimento, string chave)
        {
            CFM.ConsultaCompleta inValue = new CFM.ConsultaCompleta();
            inValue.crm = crm;
            inValue.uf = uf;
            inValue.cpf = cpf;
            inValue.dataNascimento = dataNascimento;
            inValue.chave = chave;
            return ((CFM.ServicoConsultaMedicos)(this)).ConsultaCompletaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CFM.buscarImagemResponse> CFM.ServicoConsultaMedicos.buscarImagemAsync(CFM.buscarImagem request)
        {
            return base.Channel.buscarImagemAsync(request);
        }
        
        public System.Threading.Tasks.Task<CFM.buscarImagemResponse> buscarImagemAsync(string cpf, string chave)
        {
            CFM.buscarImagem inValue = new CFM.buscarImagem();
            inValue.cpf = cpf;
            inValue.chave = chave;
            return ((CFM.ServicoConsultaMedicos)(this)).buscarImagemAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ServicoConsultaMedicosPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Não foi possível encontrar o ponto de extremidade com o nome \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ServicoConsultaMedicosPort))
            {
                return new System.ServiceModel.EndpointAddress("https://ws.cfm.org.br:8080/WebServiceConsultaMedicos/ServicoConsultaMedicos");
            }
            throw new System.InvalidOperationException(string.Format("Não foi possível encontrar o ponto de extremidade com o nome \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ServicoConsultaMedicosClient.GetBindingForEndpoint(EndpointConfiguration.ServicoConsultaMedicosPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ServicoConsultaMedicosClient.GetEndpointAddress(EndpointConfiguration.ServicoConsultaMedicosPort);
        }
        
        public enum EndpointConfiguration
        {
            
            ServicoConsultaMedicosPort,
        }
    }
}
